### ISSUE TITLE
Add support for icon class names

### ISSUE THREAD

**Issue by robframpton** [ipeychev/liferay-aui-upgrade-tool#11]
Many icons have been deprecated with the migration. We should add support to automatically change icon classes to equivalent classes/icons that are now in Portal (font awesome and glyphicons). For example

``` javascript
toolbarChildren.push(
    {
        icon: 'block'
    }
);
```

can be changed to

``` javascript
toolbarChildren.push(
    {
        icon: 'icon-ban-circle'
    }
);
```

This way we save the developer time, shuffling through the many icons available.

This can be handled similarly to the 'portlet-msg-alert 'classes

**Comment by ipeychev** [comment]
Good idea, do we have a list with these replacements?

**Comment by robframpton** [comment]
We'd have to compile it. The only issue is that some deprecated icons do
not have exact replacements.

**Comment by ipeychev** [comment]
Okay, then provide me what you have so far. I will implement the feature and we can continue extending the list with the icons.
