### ISSUE TITLE
Improper replacement of portlet-msg-info in css files

### ISSUE THREAD

**Issue by robframpton** [ipeychev/liferay-aui-upgrade-tool#3]
UT will always change '.portlet-msg-info' in css files into '.alert .alert-info'

.portlet-msg-info {
    background-color: transparent;
}

.alert .alert-info {
    background-color: transparent;
}

However this block will not actually select anything, as .alert and .alert-info are classes of the same element, .alert-info is not a child of .alert. The selector should be changed to either

.alert.alert-info {
    background-color: transparent;
}

or

.alert-info {
    background-color: transparent;
}

**Comment by robframpton** [comment]
Same thing happens with all alert classes, such as portlet-msg-error.

**Comment by ipeychev** [comment]
Robert, these classes are configurable in:
assets/css-classes.json

Would you mind to rename these to:

``` javascript
"portlet-msg-error": "alert-error",
"portlet-msg-info": "alert-info",
"portlet-msg-success": "alert-success"
```

And tell me if that fixes the issue?

**Comment by ipeychev** [comment]
Also, is that issue valid only for CSS files, or it is valid for both CSS and JSP files?

**Comment by robframpton** [comment]
The issue only exists within the JSP files. Changing <span class="portlet-msg-error"> to <span class="alert alert-error"> is correct, the issue is that it's doing the same thing in the CSS files.

So in JSPs, 'portlet-msg-error' = 'alert alert-error' is good

But in CSS, '.portlet-msg-error' = '.alert .alert-error' is bad

**Comment by robframpton** [comment]
Hey Iliyan,

This fix does not work, as now in JSPs, 'portlet-msg-error' will be changed
to 'alert-error' instead of 'alert alert-error'. We need it to do two
different things depending on the file type. So this fix works for CSS
files, but breaks it for JSPs, the way it is now in master works for JSPs,
but is broken for CSS.

**Comment by robframpton** [comment]
Yes I'll give it a shot and get back to you.

**Comment by ipeychev** [comment]
One correction - the issue is related to classes, used as selectors.
These might be in JSP files too, for example:

``` javascript
A.all('.portlet-msg-success').hide();
```

We have to change these too, like:

``` css
.alert.alert-info
```
