### ISSUE TITLE
Does not deprecate modules when script tag has position="inline"

### ISSUE THREAD

**Issue by robframpton** [ipeychev/liferay-aui-upgrade-tool#4]
UT ignores deprecated modules when the aui:script tag has the position property. For example.

```
<aui:script position="inline" use="aui-dialog,aui-dialog-iframe">
```

In this situation aui-dialog-iframe would not receive the -deprecated suffix. However, 

```
 <aui:script use="aui-dialog,aui-dialog-iframe">
```

would receive the -deprecated suffix.

**Comment by ipeychev** [comment]
Good, thanks, will fix that!
