### ISSUE TITLE
aui prefixes in classes are missed in JSP scriptlets

### ISSUE THREAD

**Issue by robframpton** [ipeychev/liferay-aui-upgrade-tool#5]
If a css class is set as a string inside of a JSP scriptlet, the aui prefix is not deleted. For example.

```
<liferay-ui:icon
    cssClass='<%= showConnectedRequestedIcon ? "disabled" : "disabled aui-helper-hidden" %>'
/>
```

In this situation, aui-helper-hidden will remain the same.

**Comment by ipeychev** [comment]
I don't see the example, could you edit it and format it following this:
https://help.github.com/articles/github-flavored-markdown#syntax-highlighting

**Comment by robframpton** [comment]
Sorry about that Iliyan, you should be able to read it now.
