### ISSUE TITLE
Add support for namespacing io request parameters

### ISSUE THREAD

**Issue by robframpton** [ipeychev/liferay-aui-upgrade-tool#8]
Currently almost all io requests without namespaced parameters do not work. We should add functionality to add namespaces for io request parameters.

```
//Old IO request

A.io.request(
    url,
    {
        data: {
            userId: userId
        },
        dataType: 'json'
    }
);

//New IO request

A.io.request(
    url,
    {
        data: {
            <portlet:namespace />userId: userId
        },
        dataType: 'json'
    }
);
```

The fix will be different between JSP and JS files, the above example would fix an io request in a JSP. The following would be the fix for a JS file.

```
//Old IO request

A.io.request(
    url,
    {
        data: {
            userId: userId
        },
        dataType: 'json'
    }
);

//New IO request

A.io.request(
    url,
    {
        data: instance.ns(
            {
                userId: userId
            }
        ),
        dataType: 'json'
    }
);
```

**Comment by ipeychev** [comment]
This one we can implement, but it will be fragile - what if we have already in data: { ... } properly namespaced attributes?

**Comment by robframpton** [comment]
I think that we can maybe just leave this functionality out, Nate suggested
that we notify the developers when they are executing an io request. Maybe
some kind of a warning message that's commented out in the code.
